"""add is_default unique index to accounts

Revision ID: 12ea61381266
Revises: b95c4d3ab47e
Create Date: 2026-07-11 18:13:07.361607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ea61381266'
down_revision: Union[str, Sequence[str], None] = 'b95c4d3ab47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    op.create_index(
        'ix_accounts_single_default',
        'accounts',
        ['is_default'],
        unique=True,
        postgresql_where=sa.text('is_default = true')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_default')
    # ### end Alembic commands ###
