"""modify timeframe column

Revision ID: 5e4ab6e91477
Revises: bcb99f2d9a17
Create Date: 2026-04-16 00:25:14.341492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4ab6e91477'
down_revision: Union[str, Sequence[str], None] = 'bcb99f2d9a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_notes', sa.Column('time_frame', sa.Integer(), nullable=True))
    op.drop_column('trade_notes', 'time_Frame')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_notes', sa.Column('time_Frame', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('trade_notes', 'time_frame')
    # ### end Alembic commands ###
