"""add SignalEdgeSheet

Revision ID: b95c4d3ab47e
Revises: 3fb46caaada0
Create Date: 2026-06-20 21:44:42.823181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95c4d3ab47e'
down_revision: Union[str, Sequence[str], None] = '3fb46caaada0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_edge_sheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Enum('GOLD', 'NASDAQ', 'OIL', name='asset_id_enum'), nullable=False),
    sa.Column('hour_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('day_open', sa.Float(), nullable=False),
    sa.Column('day_high', sa.Float(), nullable=False),
    sa.Column('day_low', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('basis', sa.JSON(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('bull', sa.Integer(), nullable=False),
    sa.Column('bear', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'hour_at', name='uq_asset_hour')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_edge_sheets')
    # ### end Alembic commands ###
