"""add timeframe column

Revision ID: bcb99f2d9a17
Revises: a871273bbcb0
Create Date: 2026-04-16 00:24:45.312246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb99f2d9a17'
down_revision: Union[str, Sequence[str], None] = 'a871273bbcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_notes', sa.Column('time_Frame', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_notes', 'time_Frame')
    # ### end Alembic commands ###
