"""add lock_enabled

Revision ID: d973e6cf3e87
Revises: 12ea61381266
Create Date: 2026-08-02 10:47:07.281783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd973e6cf3e87'
down_revision: Union[str, Sequence[str], None] = '12ea61381266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('lock_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_accounts_single_default'), table_name='accounts', postgresql_where='(is_default = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_single_default'), 'accounts', ['is_default'], unique=True, postgresql_where='(is_default = true)')
    op.drop_column('accounts', 'lock_enabled')
    # ### end Alembic commands ###
