"""add TradeLock since column

Revision ID: f3a495800ff6
Revises: 06a0815a900d
Create Date: 2026-08-03 19:03:45.615924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3a495800ff6'
down_revision: Union[str, Sequence[str], None] = '06a0815a900d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_locks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_locks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unlocked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('consec_loss_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('trade_locks_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_locks_pkey')),
    sa.UniqueConstraint('account_id', name=op.f('trade_locks_account_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
