"""add password_encrypted to account

Revision ID: f563d4d59e02
Revises: ef83cf6ff066
Create Date: 2026-04-08 02:02:47.976127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f563d4d59e02'
down_revision: Union[str, Sequence[str], None] = 'ef83cf6ff066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('password_encrypted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'password_encrypted')
    # ### end Alembic commands ###
