# generate_terminal_configs.py
#
# lock_enabled=True인 계좌들을 DB에서 읽어서
#   C:\mt5\{account_number}\config.ini
#   C:\mt5\{account_number}\MQL5\presets\{account_number}_lock.set
# 를 자동 생성한다.
#
# 실행: python -m app.generate_terminal_configs
#
# 주의:
#   - 이 스크립트는 폴더/파일만 만들어줌. 실제 MT5 설치(포터블 카피)와
#     계좌당 최초 1회 수동 로그인(+비밀번호 저장 체크)은 직접 해야 함.
#   - Symbol은 계좌별로 다를 수 있어서 SYMBOL_OVERRIDES에서 지정, 없으면 기본값 사용.
#   - Broker 모델의 서버 필드명이 다르면 broker.server 부분만 맞춰서 고치면 됨.

import asyncio
import os
from sqlalchemy import select
from sqlalchemy.orm import selectinload

from db.session import AsyncSessionLocal
from db.models.account import Account

from services.crypto import CryptoService

class GenerateTerminalConfig:

    from util.paths import TERMINAL_BASE_DIR   # .env TRADEROS_MT5_DIR (기본 C:\mt5)
    GATEWAY_URL = "http://127.0.0.1:8000"   # EA가 poll할 메인 게이트웨이 주소
    DEFAULT_SYMBOL = "XAUUSD"
    DEFAULT_PERIOD = "H1"
    EXPERT_NAME = "tradeLock"   # 시작 시 자동으로 붙일 EA (mt5_ea/tradeLock.ex5 를 서버가 데이터 폴더에 복사함)


    def _config_ini_content(login: str, password: str, server: str, set_filename: str, symbol: str) -> str:
        return f"""; auto-generated by generate_terminal_configs.py
; Password 항목 없음 - 계좌당 최초 1회 수동 로그인 + 비밀번호 저장 필요

[Common]
Login={login}
Password={password}
Server={server}

[Experts]
AllowLiveTrading=1
AllowDllImport=0
Enabled=1

[StartUp]
Expert={GenerateTerminalConfig.EXPERT_NAME}
ExpertParameters={set_filename}
Symbol={symbol}
Period={GenerateTerminalConfig.DEFAULT_PERIOD}
"""


    def _set_file_content() -> str:
        """
        TradeLock_EA.mq5의 input 이름과 정확히 일치해야 함.
        account_id는 DB의 accounts.id (락 시스템 내부 식별자) - account_number(브로커 계좌번호)와 다름에 주의.
        """
        return (
            f"InpServerUrl={GenerateTerminalConfig.GATEWAY_URL}\n"
            f"InpPollSeconds=3\n"
            f"InpApiKey=\n"
            f"InpCloseAllSymbols=true\n"   # EA 기본값과 같게: 잠금 중엔 모든 종목의 새 포지션 청산
        )

    @staticmethod
    def _known_chart_symbol(account_number: str) -> str | None:
        """워커가 MT5에서 확인해 둔 이 계좌의 실제 종목 이름 (trade_lock_worker._remember_chart_symbol)"""
        import json
        path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "chart_symbols.json")
        try:
            return json.load(open(path, encoding="utf-8")).get(str(account_number)) or None
        except (OSError, ValueError):
            return None

    @staticmethod
    def _chart_symbol(broker) -> str:
        """시작 차트 종목. 브로커 번호가 아니라 서버/브로커 이름으로 판단
        (관리 화면에서 새 서버로 계좌를 추가하면 브로커 번호가 새로 생기기 때문).
        인피녹스는 XAUUSD+, 그 외(한텍 등)는 XAUUSD.
        ※ tradeLock EA는 InpCloseAllSymbols=true 라 차트 종목과 상관없이 계좌 전체를 감시함."""
        text = f"{getattr(broker, 'server', '') or ''} {getattr(broker, 'name', '') or ''}".lower()
        return "XAUUSD+" if "infinox" in text else "XAUUSD"

    @staticmethod
    async def main():
        crypto = CryptoService()

        async with AsyncSessionLocal() as db:
            result = await db.execute(
                select(Account)
                .options(selectinload(Account.broker))
                .where(Account.lock_enabled.is_(True))
            )
            accounts = result.scalars().all()

        if not accounts:
            print("lock_enabled=True인 계좌가 없습니다.")
            return

        for acc in accounts:
            # broker.server 필드명이 실제 Broker 모델과 다르면 여기만 수정
            server_name = getattr(acc.broker, "server", None) or "UNKNOWN-SERVER"

            symbol = (GenerateTerminalConfig._known_chart_symbol(acc.account_number)
                      or GenerateTerminalConfig._chart_symbol(acc.broker))

            # symbol = GenerateTerminalConfig.SYMBOL_OVERRIDES.get(
            #     acc.account_number, 
            #     GenerateTerminalConfig.DEFAULT_SYMBOL
            # )
            
            if not acc.password_encrypted:
                print(f"  ⚠ account_number={acc.account_number}: password_encrypted가 비어있음 - 스킵")
                continue
            try:
                password = crypto.decrypt(acc.password_encrypted)
            except Exception:
                # 다른 암호화 키로 저장된 비밀번호 (예: .env 의 FERNET_KEY 를 지웠거나, data 폴더만 다른 PC에서 복사)
                # → 이 계좌만 건너뛰고 서버는 계속 켬. 관리 화면에서 비밀번호를 다시 넣으면 해결
                print(f"  ⚠ account_number={acc.account_number}: 저장된 비밀번호를 풀 수 없습니다 (암호화 키가 다름). "
                      f"관리 화면 계좌 탭에서 '비밀번호 변경'으로 다시 입력하세요. - 스킵")
                continue

            terminal_dir = os.path.join(GenerateTerminalConfig.TERMINAL_BASE_DIR, acc.account_number)
            presets_dir = os.path.join(terminal_dir, "MQL5", "presets")
            os.makedirs(presets_dir, exist_ok=True)

            set_filename = f"{acc.account_number}_lock.set"

            config_path = os.path.join(terminal_dir, "config.ini")

            with open(config_path, "w", encoding="utf-8") as f:
                f.write(GenerateTerminalConfig._config_ini_content(
                    acc.account_number, 
                    password,
                    server_name, 
                    set_filename, 
                    symbol
                ))
            print(f"[생성] {config_path}")

            set_path = os.path.join(presets_dir, set_filename)
            with open(set_path, "w", encoding="utf-8") as f:
                f.write(GenerateTerminalConfig._set_file_content())
            print(f"[생성] {set_path}")

            if server_name == "UNKNOWN-SERVER":
                print(f"  ⚠ account_number={acc.account_number}: broker.server 값을 못 찾음 - 직접 채워넣어야 함")

        print("\n남은 수동 작업:")
        print("1) 각 폴더에 포터블 MT5 설치 (같은 설치본 복사)")
        print("2) 계좌당 최초 1회 GUI로 수동 로그인 + '비밀번호 저장' 체크")
        print("3) (자동) 서버가 터미널을 띄울 때 mt5_ea/tradeLock.ex5 를 데이터 폴더에 복사함")
        print("4) WebRequest 허용 목록에 게이트웨이 URL 등록 (도구>옵션>Expert Advisors)")


if __name__ == "__main__":
    asyncio.run(GenerateTerminalConfig.main())